### ISSUE TITLE
Back Office

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/recrutement2017#1]
Salut ;)

Alors comme on approche de la finalisation, je propose d'inscrire dans ce ticket l'ensemble des fonctions dont on peut avoir besoin.

**Authentification**
- Accès via identifiant Galette
- Possibilité de limiter l'accès par une personne a une zone géographique
- accès générique pour le bureau et une potentielle équipe élection, géographique pour les autres accès
- La suppression des données doit être possible (cas spam ...)

**Page d'accueil une fois authentifié**
- Une informations sur les dernières inscriptions depuis la dernière connexion
- Une informations "statistiques" : nombre de candidats, nombre de suppléant, nombre de mandataire, trinôme complet

**Page de gestion/Affectation**
- Cette page a pour objectif de valider un trinôme sur une circonscription (On est proche d'une liaison gerermacampagne la ...)
- L'objectif et d'aider l'équipe élection à fixer les circonscriptions

**Page Liste**
- Cette page permet l'affichage de la liste des inscrits avec filtre possible

**Comment by farlistener** [comment]
Tu peux me splitter la demande en brique élémentaire ?

**Comment by Farocs** [comment]
C'est fait :)
