### ISSUE TITLE
[BO] Authentification

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/recrutement2017#10]
- Accès via identifiant Galette
- Possibilité de limiter l'accès par une personne a une zone géographique
- accès générique pour le bureau et une potentielle équipe élection, géographique pour les autres accès
- La suppression des données doit être possible (cas spam ...)

**Comment by farlistener** [comment]
Accès via identifiant Galette : OK
accès générique pour une équipe élection : OK

Le reste n'est pas à l'ordre du jour
