### ISSUE TITLE
[BO] Le lien arrière Guichet/accueil même sur une page sans information

### ISSUE THREAD

**Issue by Farocs** [PartiPirate/recrutement2017#16]
Idéalement, quelques stats générales serait utile sur cette page :
- nombre de candidats/suppléant/Mandataire
- Equilibre Homme/Femme
- Nombre de personne contacté
- Nombre de personne à contacter
- Une carte des circo de France avec les infos géographique ?

**Comment by farlistener** [comment]
"Une carte des circo de France avec les infos géographique ?" est une autre problématique
